//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportEasy.Model.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SportEasy.Model.Localization.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr-FR.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string string_Add {
            get {
                return ResourceManager.GetString("string_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendredi.
        /// </summary>
        public static string string_Add_Friday {
            get {
                return ResourceManager.GetString("string_Add_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lundi.
        /// </summary>
        public static string string_Add_Monday {
            get {
                return ResourceManager.GetString("string_Add_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samedi.
        /// </summary>
        public static string string_Add_Saturday {
            get {
                return ResourceManager.GetString("string_Add_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimanche.
        /// </summary>
        public static string string_Add_Sunday {
            get {
                return ResourceManager.GetString("string_Add_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeudi.
        /// </summary>
        public static string string_Add_Thurdsay {
            get {
                return ResourceManager.GetString("string_Add_Thurdsay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mardi.
        /// </summary>
        public static string string_Add_Tuesday {
            get {
                return ResourceManager.GetString("string_Add_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercredi.
        /// </summary>
        public static string string_Add_Wesneday {
            get {
                return ResourceManager.GetString("string_Add_Wesneday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l&apos;appli des amateurs.
        /// </summary>
        public static string string_AppSubTitle {
            get {
                return ResourceManager.GetString("string_AppSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SportEasy.
        /// </summary>
        public static string string_AppTitle {
            get {
                return ResourceManager.GetString("string_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avr..
        /// </summary>
        public static string string_April {
            get {
                return ResourceManager.GetString("string_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etes vous disponible ?.
        /// </summary>
        public static string string_AreYoufree {
            get {
                return ResourceManager.GetString("string_AreYoufree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aout.
        /// </summary>
        public static string string_August {
            get {
                return ResourceManager.GetString("string_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calendrier.
        /// </summary>
        public static string string_Calendar {
            get {
                return ResourceManager.GetString("string_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to se connecter.
        /// </summary>
        public static string string_Connect {
            get {
                return ResourceManager.GetString("string_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec..
        /// </summary>
        public static string string_December {
            get {
                return ResourceManager.GetString("string_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to déconnexion.
        /// </summary>
        public static string string_Disconnect {
            get {
                return ResourceManager.GetString("string_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ne jouent pas.
        /// </summary>
        public static string string_DontPlay {
            get {
                return ResourceManager.GetString("string_DontPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string string_Email {
            get {
                return ResourceManager.GetString("string_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fév..
        /// </summary>
        public static string string_February {
            get {
                return ResourceManager.GetString("string_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prénom.
        /// </summary>
        public static string string_Firstname {
            get {
                return ResourceManager.GetString("string_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matchs.
        /// </summary>
        public static string string_Games {
            get {
                return ResourceManager.GetString("string_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        public static string string_Info {
            get {
                return ResourceManager.GetString("string_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Janv..
        /// </summary>
        public static string string_January {
            get {
                return ResourceManager.GetString("string_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juil..
        /// </summary>
        public static string string_July {
            get {
                return ResourceManager.GetString("string_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juin.
        /// </summary>
        public static string string_June {
            get {
                return ResourceManager.GetString("string_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nom.
        /// </summary>
        public static string string_Lastname {
            get {
                return ResourceManager.GetString("string_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieux.
        /// </summary>
        public static string string_Location {
            get {
                return ResourceManager.GetString("string_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mars.
        /// </summary>
        public static string string_March {
            get {
                return ResourceManager.GetString("string_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feuille de match.
        /// </summary>
        public static string string_MatchDetails {
            get {
                return ResourceManager.GetString("string_MatchDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string string_May {
            get {
                return ResourceManager.GetString("string_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peut être.
        /// </summary>
        public static string string_Maybe {
            get {
                return ResourceManager.GetString("string_Maybe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez saisir un email..
        /// </summary>
        public static string string_MissingEmail {
            get {
                return ResourceManager.GetString("string_MissingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez saisir un prénom..
        /// </summary>
        public static string string_MissingFirstname {
            get {
                return ResourceManager.GetString("string_MissingFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez saisir un nom..
        /// </summary>
        public static string string_MissingLastname {
            get {
                return ResourceManager.GetString("string_MissingLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez saisir un mot de passe..
        /// </summary>
        public static string string_MissingPassword {
            get {
                return ResourceManager.GetString("string_MissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez saisir un mot de passe de confirmation..
        /// </summary>
        public static string string_MissingPasswordConfirmed {
            get {
                return ResourceManager.GetString("string_MissingPasswordConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mes equipes.
        /// </summary>
        public static string string_MyTeams {
            get {
                return ResourceManager.GetString("string_MyTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non.
        /// </summary>
        public static string string_No {
            get {
                return ResourceManager.GetString("string_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov..
        /// </summary>
        public static string string_November {
            get {
                return ResourceManager.GetString("string_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct..
        /// </summary>
        public static string string_October {
            get {
                return ResourceManager.GetString("string_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to participant.
        /// </summary>
        public static string string_Participant {
            get {
                return ResourceManager.GetString("string_Participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mot de passe.
        /// </summary>
        public static string string_Password {
            get {
                return ResourceManager.GetString("string_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mot de passe (confirmation).
        /// </summary>
        public static string string_PasswordConfirmed {
            get {
                return ResourceManager.GetString("string_PasswordConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jouent.
        /// </summary>
        public static string string_Play {
            get {
                return ResourceManager.GetString("string_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to joueurs.
        /// </summary>
        public static string string_Players {
            get {
                return ResourceManager.GetString("string_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joue ?.
        /// </summary>
        public static string string_PlayQuestion {
            get {
                return ResourceManager.GetString("string_PlayQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDV à.
        /// </summary>
        public static string string_RdvAt {
            get {
                return ResourceManager.GetString("string_RdvAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relancer les joueurs.
        /// </summary>
        public static string string_RecallPlayers {
            get {
                return ResourceManager.GetString("string_RecallPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s&apos;inscrire.
        /// </summary>
        public static string string_Register {
            get {
                return ResourceManager.GetString("string_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sept..
        /// </summary>
        public static string string_September {
            get {
                return ResourceManager.GetString("string_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Début à.
        /// </summary>
        public static string string_StartAt {
            get {
                return ResourceManager.GetString("string_StartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ou ?.
        /// </summary>
        public static string string_WhereQuestion {
            get {
                return ResourceManager.GetString("string_WhereQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oui.
        /// </summary>
        public static string string_Yes {
            get {
                return ResourceManager.GetString("string_Yes", resourceCulture);
            }
        }
    }
}
